### ISSUE TITLE
Screenshots required in the report

### ISSUE THREAD

**Issue by yfrindel** [GHPReporter/Ghpr.MSTestV2#19]
I have some screenshots attached to my tests, so I would like to have also these screenshots in the GHPR report please.

Regards,

Yannick

**Comment by yfrindel** [comment]
Hi,

Any progress please ?

Regards

**Comment by elv1s42** [comment]
Hi @yfrindel, the work is still in progress for this one

**Comment by elv1s42** [comment]
This is now implemented for `.trx` files and should be available in the release `v0.9.11`

**Comment by elv1s42** [comment]
Released in `v0.9.11`
